### ISSUE TITLE
Make the license mandatory for public repositories

### ISSUE THREAD

**Issue by justinccdev** [yochannah/wizard#1]
I think we can/should make a license mandatory for public repositories.  This will earn us big points with the data citation crowd and is the right thing to do.  The downside is that this many annoy some people, but I think this is vastly outweighed by the upside.

**Comment by yochannah** [comment]
@justinccdev Hmm, I think I might agree. What about making it CC-BY by default, with the option to choose another if you prefer?

**Comment by justinccdev** [comment]
I see [Creative Commons mentions CC-BY as a possible license](https://creativecommons.org/about/program-areas/open-science/).  On the other hand, [Wikidata is CC0](https://www.wikidata.org/wiki/Wikidata:Database_download/en), I believe because of the difficulties of maintaining chains of attribution over facts (which arguably aren't copyrightable).

For our purposes, I think CC-BY would be okay, though I think CC0 should be an option, if not other licenses too.  Might be worth asking around.

**Comment by madprime** [comment]
:wave: following up from Twitter: I think Creative Commons encourages CC0 for data https://creativecommons.org/about/program-areas/open-data/

You might also be interested in these:
https://wiki.creativecommons.org/wiki/CC0_use_for_data
https://wiki.creativecommons.org/wiki/Data_and_CC_licenses

And these uses of CC0 which encourage (but do not legally require) attribution:
https://dp.la/news/cc0-by/
https://unsplash.com/

**Comment by yochannah** [comment]
A great licence infographic here that we might be able to be inspired from to give advice on the choices (thanks @npscience for sharing)

http://asapbio.org/licensing-faq
